info:
  contact: {}
paths:
  /process_batch:
    get:
      description: Processes a batch of items based on the provided batch size.
      parameters:
      - description: Batch size for processing
        in: query
        name: batch_size
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: Batch successfully handled!
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Process a batch of items
swagger: "2.0"
